### ISSUE TITLE
germline variants filtering

### ISSUE THREAD

**Issue by MariaCartolano** [AlexandrovLab/SigProfilerMatrixGeneratorR#1]
Hello, would it be possible to know whether the tool filters germline mutations eventually included in a vcf file? If yes, how the vcf should then look like? I have noticed that vcf files generated from various pipelines varies a lot in this respect. 
Cheers

**Comment by ebergstr** [comment]
The tool does not filter germline variants. All mutations included in the user-provided input file are used in generating the matrices.
