### ISSUE TITLE
Install reference genome issue

### ISSUE THREAD

**Issue by XinpeiYi** [AlexandrovLab/SigProfilerMatrixGeneratorR#16]
Hi, I tried both "genInstall.install('GRCh37', rsync=False, bash=True)" and "genInstall.install('GRCh37', offline_files_path='path/to/directory/containing/GRCh37.tar.gz')" to install human regerence genome, but it shows errors.

The error message is:
If I tried the first command line, it shows:

/dssg/home/acct-clslj/clslj-7/xyi/Software/anaconda3/envs/python3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz: Cannot open: No such file or directory

If I tried the second command line, it shows:

[Errno 20] Not a directory: '/dssg/home/acct-clslj/clslj-7/xyi/Software/anaconda3/envs/python3/lib/python3.11/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/hg19.fa/'

Would you like to help me to check it? Thanks!

**Comment by mdbarnesUCSD** [comment]
Hi @XinpeiYi,

Unless you have a download from the ftp server of the reference genome, you will not want to use offline_files_path.

Please reference the README for installing GRCh37:
```
library("SigProfilerMatrixGeneratorR")
install('GRCh37', rsync=FALSE, bash=TRUE)
```

Thanks!

**Comment by mdbarnesUCSD** [comment]
Please reopen this if you have any more questions.

**Comment by DittmanC** [comment]
> Hi [@XinpeiYi](https://github.com/XinpeiYi),
> 
> Unless you have a download from the ftp server of the reference genome, you will not want to use offline_files_path.
> 
> Please reference the README for installing GRCh37:
> 
> ```
> library("SigProfilerMatrixGeneratorR")
> install('GRCh37', rsync=FALSE, bash=TRUE)
> ```
> 
> Thanks!

install('GRCh37', rsync=FALSE, bash=TRUE) is not woking for me
library("SigProfilerMatrixGeneratorR")

Attaching package: ‘SigProfilerMatrixGeneratorR’

The following object is masked from ‘package:devtools’:

    install

> install('GRCh37', rsync=FALSE, bash=TRUE)
Tool       | Installed 
-----------------------
curl       | True      
wget       | True      
rsync      | True      
INFO - Downloading GRCh37...
INFO - Attempt to download from alexandrovlab failed: [Errno 110] Connection timed out
  % Total    % Received % Xferd  Average Speed  Time    Time    Time   Current
                                 Dload  Upload  Total   Spent   Left   Speed
  0      0   0      0   0      0      0      0           02:10              0
curl: (28) Failed to connect to alexandrovlab-ftp.ucsd.edu port 21 after 131046 ms: Could not connect to server
ERROR - Curl download failed with error: Command '['curl', '-o', '/oncowd01/disk1/group_WD/user/dittman/miniconda3/envs/spmg_r/lib/python3.10/site-packages/SigProfilerMatrixGenerator/references/chromosomes/tsb/GRCh37.tar.gz', 'ftp://alexandrovlab-ftp.ucsd.edu/pub/tools/SigProfilerMatrixGenerator//GRCh37.tar.gz']' returned non-zero exit status 28..
