### ISSUE TITLE
problem with txt file input format

### ISSUE THREAD

**Issue by riccardobergamin** [AlexandrovLab/SigProfilerMatrixGeneratorR#19]
Hi,
i 'm trying to extract SNV,DBS and ID counts from a txt file in the following form

<img width="892" alt="Screenshot 2024-01-31 alle 10 14 13" src="https://github.com/AlexandrovLab/SigProfilerMatrixGeneratorR/assets/72212720/746a26ef-c5b2-40b4-8f0b-5cdfd5294d66">

but i get the error : `
The given input files do not appear to be in the correct simple text format. Skipping this file:  mutations.txt
Starting matrix generation for INDELs...Completed! Elapsed time: 0.81 seconds.
Matrices generated for 1 samples with 0 errors. Total of 0 SNVs, 0 DINUCs, and 0 INDELs were successfully analyzed.
`

I put the file in the form of the example you provided in the wiki guide, but it does not seem to be correct. Could you help me to fix it? Thank you very much

**Comment by mdbarnesUCSD** [comment]
Hi @riccardobergamin,

If you are not using the latest version of SigProfilerMatrixGenerator please update to the most recent version:
`pip install --upgrade SigProfilerMatrixGenerator`

Please reach out if you are still encountering issues.

**Comment by mdbarnesUCSD** [comment]
Please re-open this issue if you are still encountering this issue.
