### ISSUE TITLE
The example.maf 'does not appear to be in the correct MAF format' for SigProfilerMatrixGeneratorR

### ISSUE THREAD

**Issue by marshelma** [AlexandrovLab/SigProfilerMatrixGeneratorR#2]
Testing the SigProfilerMatrixGeneratorR with the example.maf provided from:
https://osf.io/s93d5/wiki/3.%20Using%20the%20Tool%20-%20Input/

Runing parameters are the same as default settings:
plot=T, exome=F, bed_file=NULL, chrom_based=F, tsb_stat=F, seqInfo=F, cushion=100

The outcome is:

The given input files do not appear to be in the correct MAF format. Skipping this file:  example (1).maf
Matrices generated for 0 samples with 0 errors. Total of 0 SNVs, 0 DINUCs, and 0 INDELs were successfully analyzed.

**Comment by ebergstr** [comment]
Thank you for pointing this issue out! I recommend updating to the newest SigProfilerMatrixGenerator which should be version 1.0.25. The issue should be resolved with this update.

Best,
Erik
