### ISSUE TITLE
Unexpected keyword argument 'refgen'

### ISSUE THREAD

**Issue by ait5** [AlexandrovLab/SigProfilerMatrixGeneratorR#3]
Hi,

I am trying to run the sigprofilerextractor() function as following:

sigprofilerextractor(input_type=input_type, output=output,
		inputdata=inputdata, refgen="GRCh37",
		minsigs = 1, maxsigs = 10, genome_build = "GRCh37",
	    replicates = 5, mtype = c("96,DINUCS,ID"), init = "random", cpu = -1)

inputdata file is the 96-substitution matrix from SigProfilerMatrixGeneratorR (output/SBS/test.SBS96.all).

I am having the following error when trying to run:
**Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: sigProfilerExtractor() got an unexpected keyword argument 'refgen'**

**Comment by ebergstr** [comment]
Hi,

You should report this issue under SigProfilerExtractorR as these are developed by separate individuals.
