### ISSUE TITLE
Issue #4 - possible explanation

### ISSUE THREAD

**Issue by maia-munteanu** [AlexandrovLab/SigProfilerMatrixGeneratorR#5]
Hi!

I've gotten the error described in issue #4 (now closed) on multiple occasions before figuring out exactly why. It seems that when running SigProfilerMatrixGeneratorR, the folder inputted can only contain .vcf files. Files with other extensions or directories seem to produce this error. Could the package be modified to allow for other files in the directory, or make a note of this requirement in the docs?

Thanks,
Maia

**Comment by marcos-diazg** [comment]
Dear @maia-munteanu,

Sorry for our late reply, and thanks so much for your interest and suggestions! I just would like to clarify that SigProfilerMatrixGeneratorR also supports MAF, ICGC and simple text file formats, apart from VCF, as explained on our [wiki page](https://osf.io/s93d5/wiki/home/). Please don't hesitate to reach out if you experience any issues with the other file formats.

Thanks again,

Marcos
