### ISSUE TITLE
Input file not removed when re-running

### ISSUE THREAD

**Issue by mattjmeier** [AlexandrovLab/SigProfilerMatrixGeneratorR#6]
I came across a minor issue while running this for the first time. While attempting to get my data in the required .txt format, I was making some small corrections to the file format, but re-running the wrapper seemed to make no difference when I changed the input file in the `matrix_path` directory. I eventually realized that I needed to descend into the "input" folder (a subdirectory within `matrix_path`) and manually remove the copy there for the wrapper to re-copy the file with the correct changes.

I'm not sure if this is the way you intend the software to behave, but from my perspective it would be preferable to either 1) warn the user that changes to files in `matrix_path` are not necessarily propagated to the input directory where the function is looking, or, 2) explicitly check whether the input files have changed in `matrix_path` compared to the input directory, and re-write the input file or tell the user to delete the old copy and re-run.

**Comment by mdbarnesUCSD** [comment]
Hi @mattjmeier,

This is how it was initially implemented and is a behavior we will consider modifying in the future. If you are encountering this issue, please manually remove the `input` directory that is generated during each run to ensure that the most current files are being used.

Thanks!
