### ISSUE TITLE
Install genome problem

### ISSUE THREAD

**Issue by Glies2** [AlexandrovLab/SigProfilerMatrixGeneratorR#7]
When I trying to install("WBcel235",rsync=FALSE, bash=FALSE),
the result is
"Beginning installation. This may take up to 40 minutes to complete.
The ensembl ftp site is not currently responding.
Error in py_call_impl(callable, dots$args, dots$keywords) : SystemExit"
What should I do?
Award for your reply.

**Comment by marcos-diazg** [comment]
Dear @Glies2,

Thanks for your interest! It seems that you have an issue with your internet connection. Could you please check that you have a stable internet connection in the computer you are running SigProfilerMatrixGeneratorR? Thanks!

**Comment by marcos-diazg** [comment]
Please feel free to reopen this ticket if you are still having this issue.
